spring:
  application:
    name: DATN
  datasource:
    url: jdbc:mysql://localhost:3306/thueTro?useSSL=false&serverTimezone=UTC
    username: spring
    password: spring
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: anhdz0809@gmail.com
    password: eaipjwfvbiwqtwxr     # (khuyên: đưa vào ENV, đừng commit)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: dz4cc9vst
  api-key: "522694251414567"
  api-secret: "-K9a9VXFV-lYB8N2Y07m-XzFQmg"  # (khuyên: ENV)

app:
  jwt:
    secret: "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYQ=="
    expiration-ms: 604800000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
